CREATE DATABASE IF NOT EXISTS user_database;
USE user_database;

CREATE TABLE IF NOT EXISTS customer (
    tenant_id INT NOT NULL,
    customer_id BIGINT AUTO_INCREMENT,
    segment VARCHAR(50),
    city VARCHAR(100),
    customer_type VARCHAR(50),
    PRIMARY KEY (tenant_id, customer_id),
    KEY idx_customer_id (customer_id)
);

CREATE TABLE IF NOT EXISTS employee (
    tenant_id INT NOT NULL,
    employee_id BIGINT AUTO_INCREMENT,
    position VARCHAR(100),
    branch_id INT,
    PRIMARY KEY (tenant_id, employee_id),
    KEY idx_employee_id (employee_id)
);

CREATE TABLE IF NOT EXISTS branch (
    tenant_id INT NOT NULL,
    branch_id INT AUTO_INCREMENT,
    name VARCHAR(200),
    city VARCHAR(100),
    zone VARCHAR(100),
    PRIMARY KEY (tenant_id, branch_id),
    KEY idx_branch_id (branch_id)
);

CREATE TABLE IF NOT EXISTS payment_method (
    method_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    type VARCHAR(30) NOT NULL
);

-- ============================================
-- PAYMENT_METHODS
-- ============================================
INSERT IGNORE INTO payment_method (name, type) VALUES
('Efectivo', 'cash'),
('Tarjeta de Credito', 'card'),
('Tarjeta de Debito', 'card'),
('Transferencia Bancaria', 'transfer'),
('Pago Movil', 'digital');


-- ============================================
-- BRANCHES
-- ============================================

-- Tenant 1: (10 branches)
INSERT IGNORE INTO branch (tenant_id, name, city, zone) VALUES
(1, 'Sucursal Centro', 'Bogota', 'Centro'),
(1, 'Sucursal Norte', 'Bogota', 'Norte'),
(1, 'Sucursal Sur', 'Bogota', 'Sur'),
(1, 'Sucursal Usaquen', 'Bogota', 'Nororiente'),
(1, 'Sucursal El Poblado', 'Medellin', 'Sur'),
(1, 'Sucursal Laureles', 'Medellin', 'Occidente'),
(1, 'Sucursal Chipichape', 'Cali', 'Norte'),
(1, 'Sucursal Jardin Plaza', 'Cali', 'Sur'),
(1, 'Sucursal Buenavista', 'Barranquilla', 'Norte'),
(1, 'Sucursal Cabecera', 'Bucaramanga', 'Oriente');

-- Tenant 2: (8 branches)
INSERT IGNORE INTO branch (tenant_id, name, city, zone) VALUES
(2, 'Sucursal Miraflores', 'Lima', 'Centro'),
(2, 'Sucursal San Isidro', 'Lima', 'Norte'),
(2, 'Sucursal La Molina', 'Lima', 'Sur'),
(2, 'Sucursal Real Plaza', 'Arequipa', 'Centro'),
(2, 'Sucursal Ovalo', 'Trujillo', 'Norte'),
(2, 'Sucursal Porongoche', 'Cusco', 'Sur'),
(2, 'Sucursal Mancora', 'Piura', 'Norte'),
(2, 'Sucursal Laguna', 'Iquitos', 'Centro');

-- Tenant 3: (5 branches)
INSERT IGNORE INTO branch (tenant_id, name, city, zone) VALUES
(3, 'Sucursal Providencia', 'Santiago', 'Centro'),
(3, 'Sucursal Las Condes', 'Santiago', 'Norte'),
(3, 'Sucursal Maipu', 'Santiago', 'Sur'),
(3, 'Sucursal Rancagua', 'Rancagua', 'Centro'),
(3, 'Sucursal Concepcion', 'Concepcion', 'Norte');

-- ============================================
-- CUSTOMERS
-- ============================================

-- Tenant 1: 100 customers
INSERT IGNORE INTO customer (tenant_id, segment, city, customer_type) VALUES
(1, 'Premium', 'Bogota', 'Persona Natural'),
(1, 'Premium', 'Bogota', 'Persona Natural'),
(1, 'Premium', 'Medellin', 'Persona Natural'),
(1, 'Regular', 'Bogota', 'Persona Natural'),
(1, 'Regular', 'Bogota', 'Empresa'),
(1, 'Regular', 'Cali', 'Persona Natural'),
(1, 'Ocasional', 'Bogota', 'Persona Natural'),
(1, 'Ocasional', 'Barranquilla', 'Persona Natural'),
(1, 'Premium', 'Bucaramanga', 'Empresa'),
(1, 'Regular', 'Cartagena', 'Persona Natural'),
(1, 'Premium', 'Bogota', 'Persona Natural'),
(1, 'Regular', 'Medellin', 'Empresa'),
(1, 'Ocasional', 'Cali', 'Persona Natural'),
(1, 'Premium', 'Pereira', 'Persona Natural'),
(1, 'Regular', 'Manizales', 'Persona Natural'),
(1, 'Premium', 'Bogota', 'Empresa'),
(1, 'Regular', 'Bogota', 'Persona Natural'),
(1, 'Ocasional', 'Santa Marta', 'Persona Natural'),
(1, 'Premium', 'Villavicencio', 'Persona Natural'),
(1, 'Regular', 'Neiva', 'Empresa'),
(1, 'Premium', 'Ibague', 'Persona Natural'),
(1, 'Regular', 'Pasto', 'Persona Natural'),
(1, 'Ocasional', 'Cucuta', 'Persona Natural'),
(1, 'Premium', 'Sincelejo', 'Empresa'),
(1, 'Regular', 'Riohacha', 'Persona Natural'),
(1, 'Premium', 'Bogota', 'Persona Natural'),
(1, 'Regular', 'Medellin', 'Persona Natural'),
(1, 'Ocasional', 'Cali', 'Empresa'),
(1, 'Premium', 'Barranquilla', 'Persona Natural'),
(1, 'Regular', 'Bucaramanga', 'Persona Natural'),
(1, 'Premium', 'Cartagena', 'Empresa'),
(1, 'Regular', 'Pereira', 'Persona Natural'),
(1, 'Ocasional', 'Manizales', 'Persona Natural'),
(1, 'Premium', 'Bogota', 'Persona Natural'),
(1, 'Regular', 'Bogota', 'Empresa'),
(1, 'Premium', 'Medellin', 'Persona Natural'),
(1, 'Regular', 'Cali', 'Persona Natural'),
(1, 'Ocasional', 'Santa Marta', 'Persona Natural'),
(1, 'Premium', 'Villavicencio', 'Empresa'),
(1, 'Regular', 'Neiva', 'Persona Natural'),
(1, 'Premium', 'Ibague', 'Persona Natural'),
(1, 'Regular', 'Pasto', 'Empresa'),
(1, 'Ocasional', 'Cucuta', 'Persona Natural'),
(1, 'Premium', 'Sincelejo', 'Persona Natural'),
(1, 'Regular', 'Riohacha', 'Persona Natural'),
(1, 'Premium', 'Bogota', 'Empresa'),
(1, 'Regular', 'Medellin', 'Persona Natural'),
(1, 'Ocasional', 'Cali', 'Persona Natural'),
(1, 'Premium', 'Barranquilla', 'Persona Natural'),
(1, 'Regular', 'Bucaramanga', 'Empresa'),
(1, 'Premium', 'Cartagena', 'Persona Natural'),
(1, 'Regular', 'Pereira', 'Persona Natural'),
(1, 'Ocasional', 'Manizales', 'Empresa'),
(1, 'Premium', 'Bogota', 'Persona Natural'),
(1, 'Regular', 'Bogota', 'Persona Natural'),
(1, 'Premium', 'Medellin', 'Persona Natural'),
(1, 'Regular', 'Cali', 'Empresa'),
(1, 'Ocasional', 'Santa Marta', 'Persona Natural'),
(1, 'Premium', 'Villavicencio', 'Persona Natural'),
(1, 'Regular', 'Neiva', 'Persona Natural'),
(1, 'Premium', 'Ibague', 'Empresa'),
(1, 'Regular', 'Pasto', 'Persona Natural'),
(1, 'Ocasional', 'Cucuta', 'Persona Natural'),
(1, 'Premium', 'Sincelejo', 'Persona Natural'),
(1, 'Regular', 'Riohacha', 'Empresa'),
(1, 'Premium', 'Bogota', 'Persona Natural'),
(1, 'Regular', 'Medellin', 'Persona Natural'),
(1, 'Ocasional', 'Cali', 'Persona Natural'),
(1, 'Premium', 'Barranquilla', 'Empresa'),
(1, 'Regular', 'Bucaramanga', 'Persona Natural'),
(1, 'Premium', 'Cartagena', 'Persona Natural'),
(1, 'Regular', 'Pereira', 'Persona Natural'),
(1, 'Ocasional', 'Manizales', 'Persona Natural'),
(1, 'Premium', 'Bogota', 'Empresa'),
(1, 'Regular', 'Bogota', 'Persona Natural'),
(1, 'Premium', 'Medellin', 'Persona Natural'),
(1, 'Regular', 'Cali', 'Persona Natural'),
(1, 'Ocasional', 'Santa Marta', 'Empresa'),
(1, 'Premium', 'Villavicencio', 'Persona Natural'),
(1, 'Regular', 'Neiva', 'Persona Natural'),
(1, 'Premium', 'Ibague', 'Persona Natural'),
(1, 'Regular', 'Pasto', 'Empresa'),
(1, 'Ocasional', 'Cucuta', 'Persona Natural'),
(1, 'Premium', 'Sincelejo', 'Persona Natural'),
(1, 'Regular', 'Riohacha', 'Persona Natural'),
(1, 'Premium', 'Bogota', 'Persona Natural'),
(1, 'Regular', 'Medellin', 'Empresa'),
(1, 'Ocasional', 'Cali', 'Persona Natural'),
(1, 'Premium', 'Barranquilla', 'Persona Natural'),
(1, 'Regular', 'Bucaramanga', 'Persona Natural'),
(1, 'Premium', 'Cartagena', 'Empresa'),
(1, 'Regular', 'Pereira', 'Persona Natural'),
(1, 'Ocasional', 'Manizales', 'Persona Natural'),
(1, 'Premium', 'Bogota', 'Persona Natural'),
(1, 'Regular', 'Bogota', 'Persona Natural'),
(1, 'Premium', 'Medellin', 'Empresa'),
(1, 'Regular', 'Cali', 'Persona Natural'),
(1, 'Ocasional', 'Santa Marta', 'Persona Natural');

-- Tenant 2: 75 customers
INSERT IGNORE INTO customer (tenant_id, segment, city, customer_type) VALUES
(2, 'Gold', 'Lima', 'Persona Natural'),
(2, 'Gold', 'Lima', 'Empresa'),
(2, 'Silver', 'Lima', 'Persona Natural'),
(2, 'Silver', 'Arequipa', 'Persona Natural'),
(2, 'Bronze', 'Trujillo', 'Persona Natural'),
(2, 'Gold', 'Cusco', 'Empresa'),
(2, 'Silver', 'Piura', 'Persona Natural'),
(2, 'Bronze', 'Iquitos', 'Persona Natural'),
(2, 'Gold', 'Lima', 'Persona Natural'),
(2, 'Silver', 'Lima', 'Empresa'),
(2, 'Gold', 'Arequipa', 'Persona Natural'),
(2, 'Silver', 'Trujillo', 'Persona Natural'),
(2, 'Bronze', 'Cusco', 'Persona Natural'),
(2, 'Gold', 'Piura', 'Empresa'),
(2, 'Silver', 'Iquitos', 'Persona Natural'),
(2, 'Gold', 'Lima', 'Persona Natural'),
(2, 'Silver', 'Lima', 'Persona Natural'),
(2, 'Bronze', 'Arequipa', 'Empresa'),
(2, 'Gold', 'Trujillo', 'Persona Natural'),
(2, 'Silver', 'Cusco', 'Persona Natural'),
(2, 'Gold', 'Piura', 'Persona Natural'),
(2, 'Silver', 'Iquitos', 'Empresa'),
(2, 'Bronze', 'Lima', 'Persona Natural'),
(2, 'Gold', 'Lima', 'Persona Natural'),
(2, 'Silver', 'Arequipa', 'Persona Natural'),
(2, 'Gold', 'Trujillo', 'Empresa'),
(2, 'Silver', 'Cusco', 'Persona Natural'),
(2, 'Bronze', 'Piura', 'Persona Natural'),
(2, 'Gold', 'Iquitos', 'Persona Natural'),
(2, 'Silver', 'Lima', 'Persona Natural'),
(2, 'Gold', 'Lima', 'Empresa'),
(2, 'Silver', 'Arequipa', 'Persona Natural'),
(2, 'Bronze', 'Trujillo', 'Persona Natural'),
(2, 'Gold', 'Cusco', 'Persona Natural'),
(2, 'Silver', 'Piura', 'Empresa'),
(2, 'Gold', 'Iquitos', 'Persona Natural'),
(2, 'Silver', 'Lima', 'Persona Natural'),
(2, 'Bronze', 'Lima', 'Persona Natural'),
(2, 'Gold', 'Arequipa', 'Persona Natural'),
(2, 'Silver', 'Trujillo', 'Empresa'),
(2, 'Gold', 'Cusco', 'Persona Natural'),
(2, 'Silver', 'Piura', 'Persona Natural'),
(2, 'Bronze', 'Iquitos', 'Persona Natural'),
(2, 'Gold', 'Lima', 'Persona Natural'),
(2, 'Silver', 'Lima', 'Empresa'),
(2, 'Gold', 'Arequipa', 'Persona Natural'),
(2, 'Silver', 'Trujillo', 'Persona Natural'),
(2, 'Bronze', 'Cusco', 'Persona Natural'),
(2, 'Gold', 'Piura', 'Empresa'),
(2, 'Silver', 'Iquitos', 'Persona Natural'),
(2, 'Gold', 'Lima', 'Persona Natural'),
(2, 'Silver', 'Lima', 'Persona Natural'),
(2, 'Bronze', 'Arequipa', 'Persona Natural'),
(2, 'Gold', 'Trujillo', 'Empresa'),
(2, 'Silver', 'Cusco', 'Persona Natural'),
(2, 'Gold', 'Piura', 'Persona Natural'),
(2, 'Silver', 'Iquitos', 'Persona Natural'),
(2, 'Bronze', 'Lima', 'Empresa'),
(2, 'Gold', 'Lima', 'Persona Natural'),
(2, 'Silver', 'Arequipa', 'Persona Natural'),
(2, 'Gold', 'Trujillo', 'Persona Natural'),
(2, 'Silver', 'Cusco', 'Empresa'),
(2, 'Bronze', 'Piura', 'Persona Natural'),
(2, 'Gold', 'Iquitos', 'Persona Natural'),
(2, 'Silver', 'Lima', 'Persona Natural'),
(2, 'Gold', 'Lima', 'Persona Natural'),
(2, 'Silver', 'Arequipa', 'Empresa'),
(2, 'Bronze', 'Trujillo', 'Persona Natural'),
(2, 'Gold', 'Cusco', 'Persona Natural'),
(2, 'Silver', 'Piura', 'Persona Natural'),
(2, 'Gold', 'Iquitos', 'Empresa'),
(2, 'Silver', 'Lima', 'Persona Natural'),
(2, 'Bronze', 'Lima', 'Persona Natural');

-- Tenant 3: 50 customers
INSERT IGNORE INTO customer (tenant_id, segment, city, customer_type) VALUES
(3, 'Platinum', 'Santiago', 'Persona Natural'),
(3, 'Platinum', 'Santiago', 'Empresa'),
(3, 'Gold', 'Santiago', 'Persona Natural'),
(3, 'Gold', 'Concepcion', 'Persona Natural'),
(3, 'Silver', 'Santiago', 'Persona Natural'),
(3, 'Silver', 'Valparaiso', 'Empresa'),
(3, 'Bronze', 'Santiago', 'Persona Natural'),
(3, 'Platinum', 'Rancagua', 'Persona Natural'),
(3, 'Gold', 'Santiago', 'Persona Natural'),
(3, 'Silver', 'Concepcion', 'Empresa'),
(3, 'Platinum', 'Santiago', 'Persona Natural'),
(3, 'Gold', 'Valparaiso', 'Persona Natural'),
(3, 'Silver', 'Santiago', 'Persona Natural'),
(3, 'Bronze', 'Santiago', 'Empresa'),
(3, 'Platinum', 'Concepcion', 'Persona Natural'),
(3, 'Gold', 'Rancagua', 'Persona Natural'),
(3, 'Silver', 'Santiago', 'Persona Natural'),
(3, 'Platinum', 'Santiago', 'Persona Natural'),
(3, 'Gold', 'Santiago', 'Empresa'),
(3, 'Silver', 'Concepcion', 'Persona Natural'),
(3, 'Bronze', 'Valparaiso', 'Persona Natural'),
(3, 'Platinum', 'Santiago', 'Persona Natural'),
(3, 'Gold', 'Santiago', 'Persona Natural'),
(3, 'Silver', 'Rancagua', 'Empresa'),
(3, 'Platinum', 'Concepcion', 'Persona Natural'),
(3, 'Gold', 'Santiago', 'Persona Natural'),
(3, 'Silver', 'Santiago', 'Persona Natural'),
(3, 'Bronze', 'Concepcion', 'Persona Natural'),
(3, 'Platinum', 'Valparaiso', 'Empresa'),
(3, 'Gold', 'Santiago', 'Persona Natural'),
(3, 'Silver', 'Santiago', 'Persona Natural'),
(3, 'Platinum', 'Santiago', 'Persona Natural'),
(3, 'Gold', 'Rancagua', 'Empresa'),
(3, 'Silver', 'Concepcion', 'Persona Natural'),
(3, 'Bronze', 'Santiago', 'Persona Natural'),
(3, 'Platinum', 'Valparaiso', 'Persona Natural'),
(3, 'Gold', 'Santiago', 'Persona Natural'),
(3, 'Silver', 'Santiago', 'Empresa'),
(3, 'Platinum', 'Concepcion', 'Persona Natural'),
(3, 'Gold', 'Santiago', 'Persona Natural'),
(3, 'Silver', 'Valparaiso', 'Persona Natural'),
(3, 'Bronze', 'Santiago', 'Persona Natural'),
(3, 'Platinum', 'Santiago', 'Empresa'),
(3, 'Gold', 'Rancagua', 'Persona Natural'),
(3, 'Silver', 'Concepcion', 'Persona Natural'),
(3, 'Platinum', 'Santiago', 'Persona Natural'),
(3, 'Gold', 'Santiago', 'Persona Natural'),
(3, 'Silver', 'Valparaiso', 'Empresa'),
(3, 'Bronze', 'Santiago', 'Persona Natural'),
(3, 'Platinum', 'Concepcion', 'Persona Natural');

-- Tenant 1
INSERT IGNORE INTO employee (tenant_id, position, branch_id) VALUES
(1, 'Vendedor Senior', 301),
(1, 'Vendedor Junior', 301),
(1, 'Cajero', 301),
(1, 'Vendedor Senior', 302),
(1, 'Vendedor', 302),
(1, 'Cajero', 302),
(1, 'Vendedor Senior', 303),
(1, 'Vendedor', 303),
(1, 'Cajero', 303),
(1, 'Vendedor', 304),
(1, 'Vendedor Senior', 304),
(1, 'Supervisor', 305),
(1, 'Vendedor', 305),
(1, 'Vendedor Senior', 306),
(1, 'Cajero', 306),
(1, 'Vendedor', 307),
(1, 'Vendedor Senior', 308),
(1, 'Vendedor', 308),
(1, 'Cajero', 309),
(1, 'Vendedor Senior', 310);

-- Tenant 2
INSERT IGNORE INTO employee (tenant_id, position, branch_id) VALUES
(2, 'Vendedor Senior', 601),
(2, 'Vendedor', 601),
(2, 'Cajero', 601),
(2, 'Vendedor Senior', 602),
(2, 'Vendedor', 602),
(2, 'Supervisor', 603),
(2, 'Vendedor', 603),
(2, 'Vendedor Senior', 604),
(2, 'Cajero', 604),
(2, 'Vendedor', 605),
(2, 'Vendedor Senior', 605),
(2, 'Vendedor', 606),
(2, 'Cajero', 606),
(2, 'Vendedor Senior', 607),
(2, 'Vendedor', 607);

-- Tenant 3
INSERT IGNORE INTO employee (tenant_id, position, branch_id) VALUES
(3, 'Vendedor Senior', 801),
(3, 'Vendedor', 801),
(3, 'Cajero', 801),
(3, 'Vendedor Senior', 802),
(3, 'Vendedor', 802),
(3, 'Supervisor', 803),
(3, 'Vendedor', 803),
(3, 'Vendedor Senior', 804),
(3, 'Vendedor', 804),
(3, 'Cajero', 805);

-- ============================================
-- EMPLOYEES
-- ============================================
-- Tenant 1
INSERT IGNORE INTO employee (tenant_id, position, branch_id) VALUES
(1, 'Vendedor Senior', 301),
(1, 'Vendedor Junior', 301),
(1, 'Cajero', 301),
(1, 'Vendedor Senior', 302),
(1, 'Vendedor', 302),
(1, 'Cajero', 302),
(1, 'Vendedor Senior', 303),
(1, 'Vendedor', 303),
(1, 'Cajero', 303),
(1, 'Vendedor', 304),
(1, 'Vendedor Senior', 304),
(1, 'Supervisor', 305),
(1, 'Vendedor', 305),
(1, 'Vendedor Senior', 306),
(1, 'Cajero', 306),
(1, 'Vendedor', 307),
(1, 'Vendedor Senior', 308),
(1, 'Vendedor', 308),
(1, 'Cajero', 309),
(1, 'Vendedor Senior', 310);

-- Tenant 2
INSERT IGNORE INTO employee (tenant_id, position, branch_id) VALUES
(2, 'Vendedor Senior', 601),
(2, 'Vendedor', 601),
(2, 'Cajero', 601),
(2, 'Vendedor Senior', 602),
(2, 'Vendedor', 602),
(2, 'Supervisor', 603),
(2, 'Vendedor', 603),
(2, 'Vendedor Senior', 604),
(2, 'Cajero', 604),
(2, 'Vendedor', 605),
(2, 'Vendedor Senior', 605),
(2, 'Vendedor', 606),
(2, 'Cajero', 606),
(2, 'Vendedor Senior', 607),
(2, 'Vendedor', 607);

-- Tenant 3
INSERT IGNORE INTO employee (tenant_id, position, branch_id) VALUES
(3, 'Vendedor Senior', 801),
(3, 'Vendedor', 801),
(3, 'Cajero', 801),
(3, 'Vendedor Senior', 802),
(3, 'Vendedor', 802),
(3, 'Supervisor', 803),
(3, 'Vendedor', 803),
(3, 'Vendedor Senior', 804),
(3, 'Vendedor', 804),
(3, 'Cajero', 805);